### ISSUE TITLE
The intruduction for the distributions' formulas

### ISSUE THREAD

**Issue by longbiao1993** [tpetzoldt/FAdist#2]
I define the dllg3 and pllg3 by the formulas in https://en.wikipedia.org/wiki/Shifted_log-logistic_distribution#cite_note-Hosking97-3
, but I find this is not the same result as your code. So I want to know your the distributions' formulas about dllog3 and pllog3, and then I can transfer my parameters to your formulas.

**Comment by tpetzoldt** [comment]
Can you please send me a reproducible example? Thanks.

**Comment by longbiao1993** [comment]
Thanks, the example is below:
library(FAdist)
dllg3 <- function(x,a,b,y) ((a/b)*((x-y)/b)^(a-1))*(1+((x-y)/b)^a)^(-2)
pllg3 <- function(q,a,b,y) 1/(1+(b/(q-y))^a)
data<-rllog3(100,shape=2,scale=1,thres=10)
Fn=pllg3(data,2,1,10)
Fo=pllog3(data,shape=2,scale=1,thres=10)
print(Fn)
print(Fo)

**Comment by tpetzoldt** [comment]
The log-logistic and its shifted counterpart come with different parametrizations, see also the Wikipedia article cited by you that already contains two different forms. The original author of FAdist used obviously just another form, by first extending the logistic from **R** to the log-logistic (using `log(q)`) and then by shifting it with `thresh`. The functions used can be inspected in the source code of FAdist (`pllog3`and `pllog`) and base **R** (`plogis`), see:

```r
pllog <- function (q, shape = 1, scale = 1, lower.tail = TRUE, log.p = FALSE) {
  Fx <- plogis(log(q), location = scale, scale = shape)
  
  if (!lower.tail) 
    Fx <- 1 - Fx
  if (log.p) 
    Fx <- log(Fx)
  return(Fx)
}

pllog3 <- function (q, shape = 1, scale = 1, thres = 0, lower.tail = TRUE, 
          log.p = FALSE) {
  Fx <- pllog(q - thres, shape, scale)
  if (!lower.tail) 
    Fx <- 1 - Fx
  if (log.p) 
    Fx <- log(Fx)
  return(Fx)
}
```

Note also that Github is about code development and not a help desk. In case of further questions, please consider the [r-help mailing list](https://www.r-project.org/mail.html), [StackOverflow](https://stackoverflow.com/questions/tagged/r) for R questions, or [CrossValidated](https://stats.stackexchange.com/) for statistical questions.
